# -*- coding: utf-8 -*-
"""Classroom-Engagment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pgSOXLsx0F2Ba1o1i3Px1IrV-O_E1CwW
"""

!pip install -q ultralytics opencv-python-headless jupyter_bbox_widget pyyaml scikit-learn

from google.colab import output
output.enable_custom_widget_manager()

from google.colab import drive
drive.mount('/content/drive')

from pathlib import Path

# Your videos folder in Google Drive
VIDEOS_DIR = Path("/content/drive/MyDrive/Self-Collected-Data")

# IMPORTANT: Project folder is now inside Google Drive
PROJECT_DIR = Path("/content/drive/MyDrive/classroom_engagement_project")

# All outputs will be saved permanently here
FRAMES_DIR = PROJECT_DIR / "frames_raw"
LABELS_RAW_DIR = PROJECT_DIR / "labels_raw"
DATASET_DIR = PROJECT_DIR / "yolo_dataset"
RUNS_DIR = PROJECT_DIR / "runs"
PREDICTIONS_DIR = PROJECT_DIR / "predictions"
OUTPUT_DIR = PROJECT_DIR / "output"

# Create folders
FRAMES_DIR.mkdir(parents=True, exist_ok=True)
LABELS_RAW_DIR.mkdir(parents=True, exist_ok=True)
DATASET_DIR.mkdir(parents=True, exist_ok=True)
RUNS_DIR.mkdir(parents=True, exist_ok=True)
PREDICTIONS_DIR.mkdir(parents=True, exist_ok=True)
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

CLASS_NAMES = [
    "focused_head",
    "head_down",
    "mobile_phone",
    "laptop",
    "notebook_book"
]

CLASS_TO_ID = {name: i for i, name in enumerate(CLASS_NAMES)}

print("Project folder:", PROJECT_DIR)
print("Videos folder:", VIDEOS_DIR)
print("Frames folder:", FRAMES_DIR)
print("Labels folder:", LABELS_RAW_DIR)
print("Dataset folder:", DATASET_DIR)
print("Classes:", CLASS_TO_ID)

video_extensions = [".mp4", ".mov", ".avi", ".mkv"]

videos = []
for ext in video_extensions:
    videos.extend(list(VIDEOS_DIR.rglob(f"*{ext}")))

print("Total videos found:", len(videos))

for v in videos[:10]:
    print(v)

import cv2
import re
from tqdm import tqdm
from pathlib import Path

FRAMES_PER_VIDEO = 3
RESIZE_WIDTH = 960

def safe_name(name):
    name = Path(name).stem
    name = re.sub(r"[^a-zA-Z0-9_-]", "_", name)
    return name

def resize_keep_aspect(frame, target_width=960):
    h, w = frame.shape[:2]

    if w <= target_width:
        return frame

    scale = target_width / w
    new_h = int(h * scale)

    return cv2.resize(frame, (target_width, new_h))

for video_path in tqdm(videos):
    video_id = safe_name(video_path.name)
    out_dir = FRAMES_DIR / video_id
    out_dir.mkdir(parents=True, exist_ok=True)

    cap = cv2.VideoCapture(str(video_path))

    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

    if total_frames <= 0:
        print("Could not read frames from:", video_path)
        cap.release()
        continue

    # Select start, middle, end frames
    frame_indices = [
        0,
        total_frames // 2,
        max(total_frames - 1, 0)
    ]

    saved_count = 0

    for idx in frame_indices:
        cap.set(cv2.CAP_PROP_POS_FRAMES, idx)

        ret, frame = cap.read()

        if not ret:
            continue

        frame = resize_keep_aspect(frame, RESIZE_WIDTH)

        frame_file = out_dir / f"{video_id}_frame_{saved_count:03d}.jpg"
        cv2.imwrite(str(frame_file), frame)

        saved_count += 1

    cap.release()

print("Frame extraction completed.")
print("Total extracted frames:", len(list(FRAMES_DIR.rglob('*.jpg'))))
print("Frames saved in:", FRAMES_DIR)

import matplotlib.pyplot as plt
from PIL import Image
import random

all_images = sorted(list(FRAMES_DIR.rglob("*.jpg")))
print("Total images:", len(all_images))

sample_images = random.sample(all_images, min(9, len(all_images)))

plt.figure(figsize=(12, 8))
for i, img_path in enumerate(sample_images):
    img = Image.open(img_path)
    plt.subplot(3, 3, i + 1)
    plt.imshow(img)
    plt.axis("off")
    plt.title(img_path.parent.name)
plt.show()

!pip show jupyter_bbox_widget

import base64
from pathlib import Path
from PIL import Image

CLASS_NAMES = [
    "focused_head",
    "head_down",
    "mobile_phone",
    "laptop",
    "notebook_book"
]

CLASS_TO_ID = {name: i for i, name in enumerate(CLASS_NAMES)}

def image_to_base64(path):
    with open(path, "rb") as f:
        encoded = base64.b64encode(f.read()).decode("utf-8")
    return "data:image/jpeg;base64," + encoded

def label_path_from_image(image_path):
    image_path = Path(image_path)
    rel = image_path.relative_to(FRAMES_DIR)
    label_path = LABELS_RAW_DIR / rel.with_suffix(".txt")
    label_path.parent.mkdir(parents=True, exist_ok=True)
    return label_path

def save_yolo_labels(image_path, bboxes):
    img = Image.open(image_path)
    img_w, img_h = img.size

    label_path = label_path_from_image(image_path)

    lines = []

    for box in bboxes:
        label = box.get("label")

        if label not in CLASS_TO_ID:
            continue

        x = float(box["x"])
        y = float(box["y"])
        w = float(box["width"])
        h = float(box["height"])

        x = max(0, min(x, img_w - 1))
        y = max(0, min(y, img_h - 1))
        w = max(1, min(w, img_w - x))
        h = max(1, min(h, img_h - y))

        x_center = (x + w / 2) / img_w
        y_center = (y + h / 2) / img_h
        width = w / img_w
        height = h / img_h

        cls_id = CLASS_TO_ID[label]

        lines.append(
            f"{cls_id} {x_center:.6f} {y_center:.6f} {width:.6f} {height:.6f}"
        )

    with open(label_path, "w") as f:
        f.write("\n".join(lines))

    return label_path

import base64
from pathlib import Path
from PIL import Image

# Make sure these paths are already defined before this cell:
# FRAMES_DIR = Path("/content/drive/MyDrive/classroom_engagement_project/frames_raw")
# LABELS_RAW_DIR = Path("/content/drive/MyDrive/classroom_engagement_project/labels_raw")

# Create labels folder if it does not exist
LABELS_RAW_DIR.mkdir(parents=True, exist_ok=True)

# Final classes for annotation
CLASS_NAMES = [
    "focused_head",
    "head_down",
    "mobile_phone",
    "laptop",
    "notebook_book"
]

CLASS_TO_ID = {name: i for i, name in enumerate(CLASS_NAMES)}

print("Classes:", CLASS_TO_ID)
print("Frames folder:", FRAMES_DIR)
print("Labels folder:", LABELS_RAW_DIR)


def image_to_base64(path):
    """
    Converts image file into base64 format so it can be displayed
    inside the BBoxWidget annotation tool.
    """
    with open(path, "rb") as f:
        encoded = base64.b64encode(f.read()).decode("utf-8")

    return "data:image/jpeg;base64," + encoded


def label_path_from_image(image_path):
    """
    Creates matching YOLO label path for each image.

    Example:
    frames_raw/video1/video1_frame_000.jpg

    becomes:
    labels_raw/video1/video1_frame_000.txt
    """
    image_path = Path(image_path)

    rel = image_path.relative_to(FRAMES_DIR)

    label_path = LABELS_RAW_DIR / rel.with_suffix(".txt")

    label_path.parent.mkdir(parents=True, exist_ok=True)

    return label_path


def save_yolo_labels(image_path, bboxes):
    """
    Saves bounding boxes in YOLO format:

    class_id x_center y_center width height

    All values except class_id are normalized between 0 and 1.
    """
    image_path = Path(image_path)

    img = Image.open(image_path)
    img_w, img_h = img.size

    label_path = label_path_from_image(image_path)

    lines = []

    for box in bboxes:
        label = box.get("label")

        # Ignore unknown labels
        if label not in CLASS_TO_ID:
            continue

        x = float(box["x"])
        y = float(box["y"])
        w = float(box["width"])
        h = float(box["height"])

        # Keep boxes inside image boundaries
        x = max(0, min(x, img_w - 1))
        y = max(0, min(y, img_h - 1))
        w = max(1, min(w, img_w - x))
        h = max(1, min(h, img_h - y))

        # Convert to YOLO format
        x_center = (x + w / 2) / img_w
        y_center = (y + h / 2) / img_h
        width = w / img_w
        height = h / img_h

        cls_id = CLASS_TO_ID[label]

        lines.append(
            f"{cls_id} {x_center:.6f} {y_center:.6f} {width:.6f} {height:.6f}"
        )

    # Save label file
    with open(label_path, "w") as f:
        f.write("\n".join(lines))

    return label_path

all_images = sorted(list(FRAMES_DIR.rglob("*.jpg")))

unlabeled_images = [
    img for img in all_images
    if not label_path_from_image(img).exists()
]

print("Total images:", len(all_images))
print("Remaining unlabeled images:", len(unlabeled_images))

from IPython.display import display, clear_output
import ipywidgets as widgets
from jupyter_bbox_widget import BBoxWidget
import os

# Recalculate remaining images
all_images = sorted(list(FRAMES_DIR.rglob("*.jpg")))

unlabeled_images = [
    img for img in all_images
    if not label_path_from_image(img).exists()
]

print("Remaining unlabeled images:", len(unlabeled_images))

state = {
    "index": 0,
    "widget": None,
    "image_path": None
}

def render():
    clear_output(wait=True)

    if state["index"] >= len(unlabeled_images):
        print("All images annotated.")
        return

    image_path = unlabeled_images[state["index"]]
    state["image_path"] = image_path

    save_btn = widgets.Button(description="Save & Next", button_style="success")
    empty_btn = widgets.Button(description="No Object / Empty", button_style="warning")
    skip_btn = widgets.Button(description="Skip", button_style="")
    delete_btn = widgets.Button(description="Delete Bad Image", button_style="danger")

    widget = BBoxWidget(
        image=image_to_base64(image_path),
        classes=CLASS_NAMES
    )

    state["widget"] = widget

    def save_and_next(btn):
        save_yolo_labels(state["image_path"], state["widget"].bboxes)
        state["index"] += 1
        render()

    def save_empty_and_next(btn):
        label_path = label_path_from_image(state["image_path"])
        with open(label_path, "w") as f:
            f.write("")
        state["index"] += 1
        render()

    def skip_image(btn):
        state["index"] += 1
        render()

    def delete_bad_image(btn):
        image_path = state["image_path"]
        label_path = label_path_from_image(image_path)

        if image_path.exists():
            os.remove(image_path)

        if label_path.exists():
            os.remove(label_path)

        state["index"] += 1
        render()

    save_btn.on_click(save_and_next)
    empty_btn.on_click(save_empty_and_next)
    skip_btn.on_click(skip_image)
    delete_btn.on_click(delete_bad_image)

    print(f"Image: {state['index'] + 1} / {len(unlabeled_images)}")
    print("File:", image_path.name)
    print("Video:", image_path.parent.name)
    print("Classes:", CLASS_NAMES)
    print("Draw box → choose class → click widget Submit → click Save & Next")

    display(widgets.HBox([save_btn, empty_btn, skip_btn, delete_btn]))
    display(widget)

render()

!pip install -q ultralytics opencv-python-headless pyyaml

from collections import Counter

class_counts = Counter()
empty_label_files = 0

# Define the 'labels' variable by listing all .txt files in LABELS_RAW_DIR
labels = list(LABELS_RAW_DIR.rglob("*.txt"))

for label_file in labels:
    text = label_file.read_text().strip()

    if text == "":
        empty_label_files += 1
        continue

    for line in text.splitlines():
        parts = line.strip().split()

        if len(parts) == 5:
            cls_id = int(parts[0])
            class_counts[CLASS_NAMES[cls_id]] += 1

print("Empty label files:", empty_label_files)
print("Class distribution:")

for cls in CLASS_NAMES:
    print(cls, ":", class_counts[cls])

invalid_labels = []

for label_file in LABELS_RAW_DIR.rglob("*.txt"):
    text = label_file.read_text().strip()

    if text == "":
        continue

    lines = text.splitlines()

    for line_no, line in enumerate(lines, start=1):
        parts = line.strip().split()

        if len(parts) != 5:
            invalid_labels.append((label_file, line_no, line))
            continue

        try:
            cls_id = int(parts[0])
            x, y, w, h = map(float, parts[1:])

            if cls_id < 0 or cls_id >= len(CLASS_NAMES):
                invalid_labels.append((label_file, line_no, line))

            if not (0 <= x <= 1 and 0 <= y <= 1 and 0 < w <= 1 and 0 < h <= 1):
                invalid_labels.append((label_file, line_no, line))

        except:
            invalid_labels.append((label_file, line_no, line))

print("Invalid label lines:", len(invalid_labels))

for item in invalid_labels[:10]:
    print(item)

import cv2
import random
import matplotlib.pyplot as plt

def draw_yolo_boxes(img_path):
    img = cv2.imread(str(img_path))
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    h, w = img.shape[:2]
    label_path = label_path_from_image(img_path)

    if label_path.exists():
        text = label_path.read_text().strip()

        if text:
            for line in text.splitlines():
                parts = line.strip().split()

                if len(parts) != 5:
                    continue

                cls_id, xc, yc, bw, bh = parts
                cls_id = int(cls_id)
                xc, yc, bw, bh = map(float, [xc, yc, bw, bh])

                x1 = int((xc - bw / 2) * w)
                y1 = int((yc - bh / 2) * h)
                x2 = int((xc + bw / 2) * w)
                y2 = int((yc + bh / 2) * h)

                cv2.rectangle(img, (x1, y1), (x2, y2), (255, 0, 0), 2)
                cv2.putText(
                    img,
                    CLASS_NAMES[cls_id],
                    (x1, max(y1 - 5, 20)),
                    cv2.FONT_HERSHEY_SIMPLEX,
                    0.6,
                    (255, 0, 0),
                    2
                )

    return img

# Define labeled_images, assuming all_images are now labeled
labeled_images = all_images

sample_images = random.sample(labeled_images, min(9, len(labeled_images)))

plt.figure(figsize=(15, 10))

for i, img_path in enumerate(sample_images):
    img = draw_yolo_boxes(img_path)
    plt.subplot(3, 3, i + 1)
    plt.imshow(img)
    plt.axis("off")
    plt.title(img_path.name)

plt.show()

import random
import shutil
from collections import Counter

# Clear old YOLO dataset if it exists
if DATASET_DIR.exists():
    shutil.rmtree(DATASET_DIR)

for split in ["train", "val", "test"]:
    (DATASET_DIR / "images" / split).mkdir(parents=True, exist_ok=True)
    (DATASET_DIR / "labels" / split).mkdir(parents=True, exist_ok=True)

video_ids = sorted(list(set(img.parent.name for img in labeled_images)))

print("Videos with annotations:", len(video_ids))

random.seed(42)
random.shuffle(video_ids)

n = len(video_ids)

train_end = int(0.70 * n)
val_end = int(0.85 * n)

train_videos = set(video_ids[:train_end])
val_videos = set(video_ids[train_end:val_end])
test_videos = set(video_ids[val_end:])

print("Train videos:", len(train_videos))
print("Val videos:", len(val_videos))
print("Test videos:", len(test_videos))

def get_split(video_id):
    if video_id in train_videos:
        return "train"
    elif video_id in val_videos:
        return "val"
    else:
        return "test"

copied = Counter()

for img_path in labeled_images:
    video_id = img_path.parent.name
    split = get_split(video_id)

    unique_name = f"{video_id}_{img_path.name}"

    dst_img = DATASET_DIR / "images" / split / unique_name
    dst_label = DATASET_DIR / "labels" / split / unique_name.replace(".jpg", ".txt")

    src_label = label_path_from_image(img_path)

    shutil.copy2(img_path, dst_img)
    shutil.copy2(src_label, dst_label)

    copied[split] += 1

print("Copied images:")
print(copied)

print("Dataset saved at:", DATASET_DIR)

import yaml

data_yaml = {
    "path": str(DATASET_DIR),
    "train": "images/train",
    "val": "images/val",
    "test": "images/test",
    "nc": len(CLASS_NAMES),
    "names": CLASS_NAMES
}

DATA_YAML_PATH = DATASET_DIR / "data.yaml"

with open(DATA_YAML_PATH, "w") as f:
    yaml.dump(data_yaml, f, sort_keys=False)

print(open(DATA_YAML_PATH).read())

from ultralytics import YOLO

model = YOLO("yolov8n.pt")

results = model.train(
    data=str(DATA_YAML_PATH),
    epochs=25,
    imgsz=640,
    batch=8,
    patience=10,
    workers=2,
    project=str(RUNS_DIR),
    name="classroom_yolo_transfer_learning",
    seed=42,

    degrees=5,
    translate=0.05,
    scale=0.25,
    fliplr=0.5,
    hsv_h=0.015,
    hsv_s=0.4,
    hsv_v=0.3
)

from pathlib import Path
from IPython.display import Image as IPImage, display

RUN_DIR = Path("/content/drive/MyDrive/classroom_engagement_project/runs/classroom_yolo_transfer_learning-2")

results_img = RUN_DIR / "results.png"
confusion_img = RUN_DIR / "confusion_matrix.png"
best_model_path = RUN_DIR / "weights" / "best.pt"

print("Run folder:", RUN_DIR)
print("Best model exists:", best_model_path.exists())
print("Results image exists:", results_img.exists())
print("Confusion matrix exists:", confusion_img.exists())

display(IPImage(filename=str(results_img)))
display(IPImage(filename=str(confusion_img)))

from ultralytics import YOLO

best_model = YOLO(str(best_model_path))

best_model_path = RUN_DIR / "weights" / "best.pt"

best_model = YOLO(str(best_model_path))

metrics = best_model.val(
    data=str(DATA_YAML_PATH),
    split="test",
    imgsz=640,
    batch=4
)

print(metrics)

test_images_dir = DATASET_DIR / "images" / "test"

pred_results = best_model.predict(
    source=str(test_images_dir),
    conf=0.25,
    save=True,
    project=str(PREDICTIONS_DIR),
    name="test_images"
)

print("Predictions saved at:", PREDICTIONS_DIR / "test_images")

pred_dir = PREDICTIONS_DIR / "test_images"
pred_images = list(pred_dir.glob("*.jpg"))

print("Prediction images:", len(pred_images))

for img_path in pred_images[:10]:
    display(IPImage(filename=str(img_path)))

from pathlib import Path
import shutil

PROJECT_DIR = Path("/content/drive/MyDrive/classroom_engagement_project")

RUN_DIR = PROJECT_DIR / "runs" / "classroom_yolo_transfer_learning-2"
best_model_path = RUN_DIR / "weights" / "best.pt"

DATA_YAML_PATH = PROJECT_DIR / "yolo_dataset" / "data.yaml"

FINAL_OUTPUT_DIR = PROJECT_DIR / "final_output"
FINAL_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

print("Best model exists:", best_model_path.exists())
print("Data YAML exists:", DATA_YAML_PATH.exists())

shutil.copy2(best_model_path, FINAL_OUTPUT_DIR / "classroom_engagement_yolov8n_best.pt")
shutil.copy2(DATA_YAML_PATH, FINAL_OUTPUT_DIR / "data.yaml")

print("Final files saved in:", FINAL_OUTPUT_DIR)
print("Model:", FINAL_OUTPUT_DIR / "classroom_engagement_yolov8n_best.pt")
print("YAML:", FINAL_OUTPUT_DIR / "data.yaml")

from collections import Counter

def classify_image_engagement(result):
    labels = []

    if result.boxes is not None and len(result.boxes) > 0:
        cls_ids = result.boxes.cls.cpu().numpy().astype(int)
        labels = [CLASS_NAMES[i] for i in cls_ids]

    labels_set = set(labels)

    if "head_down" in labels_set and "mobile_phone" in labels_set:
        return "mobile_usage", labels

    if "head_down" in labels_set and "notebook_book" in labels_set:
        return "note_taking", labels

    if "laptop" in labels_set:
        return "laptop_usage", labels

    if "focused_head" in labels_set:
        return "focused", labels

    if "head_down" in labels_set:
        return "uncertain_head_down", labels

    return "unknown", labels

sample_img = str(test_images_dir / pred_images[0].name) if pred_images else str(list(test_images_dir.glob("*.jpg"))[0])

results = best_model.predict(sample_img, conf=0.25)

state, detected_labels = classify_image_engagement(results[0])

print("Engagement state:", state)
print("Detected labels:", detected_labels)

import matplotlib.pyplot as plt
import cv2
from pathlib import Path

# Get all test images
test_image_paths = sorted(list(test_images_dir.glob("*.jpg")))

print("Total test images:", len(test_image_paths))

# Image 2 means index 1
IMAGE_INDEX = 1

if len(test_image_paths) <= IMAGE_INDEX:
    print("There is no image 2 in the test folder.")
else:
    sample_img = str(test_image_paths[IMAGE_INDEX])

    print("Selected image:", sample_img)

    # Predict
    results = best_model.predict(sample_img, conf=0.25)

    # Engagement classification
    state, detected_labels = classify_image_engagement(results[0])

    print("Engagement state:", state)
    print("Detected labels:", detected_labels)

    # Show predicted image with boxes
    annotated_img = results[0].plot()

    # Convert BGR to RGB for matplotlib
    annotated_img = cv2.cvtColor(annotated_img, cv2.COLOR_BGR2RGB)

    plt.figure(figsize=(10, 8))
    plt.imshow(annotated_img)
    plt.axis("off")
    plt.title(f"Engagement State: {state}")
    plt.show()

test_image_paths = sorted(list(test_images_dir.glob("*.jpg")))

summary = []

for img_path in test_image_paths:
    results = best_model.predict(str(img_path), conf=0.25, verbose=False)
    state, detected_labels = classify_image_engagement(results[0])

    summary.append({
        "image": img_path.name,
        "state": state,
        "detected_labels": ", ".join(detected_labels)
    })

import pandas as pd

df_summary = pd.DataFrame(summary)
df_summary.head()

sample_img = str(test_images_dir / pred_images[0].name) if pred_images else str(list(test_images_dir.glob("*.jpg"))[0])

results = best_model.predict(sample_img, conf=0.25)

state, detected_labels = classify_image_engagement(results[0])

print("Engagement state:", state)
print("Detected labels:", detected_labels)

import pandas as pd
import matplotlib.pyplot as plt
import cv2

test_image_paths = sorted(list(test_images_dir.glob("*.jpg")))

summary = []
display_images = []

for img_path in test_image_paths:
    results = best_model.predict(str(img_path), conf=0.25, verbose=False)
    state, detected_labels = classify_image_engagement(results[0])

    summary.append({
        "image": img_path.name,
        "state": state,
        "detected_labels": ", ".join(detected_labels)
    })

    # Save annotated image for display
    annotated_img = results[0].plot()
    annotated_img = cv2.cvtColor(annotated_img, cv2.COLOR_BGR2RGB)

    display_images.append({
        "image_name": img_path.name,
        "state": state,
        "detected_labels": detected_labels,
        "annotated_img": annotated_img
    })

df_summary = pd.DataFrame(summary)

print("Prediction Summary:")
display(df_summary.head())



plt.tight_layout()
plt.show()

csv_path = FINAL_OUTPUT_DIR / "test_engagement_summary.csv"
df_summary.to_csv(csv_path, index=False)

print("Saved:", csv_path)

from ultralytics import YOLO

RUN_DIR = RUNS_DIR / "classroom_yolo_transfer_learning"
best_model_path = RUN_DIR / "weights" / "best.pt"

best_model = YOLO(str(best_model_path))

metrics = best_model.val(
    data=str(DATA_YAML_PATH),
    split="test",
    imgsz=640,
    batch=4
)

print(metrics)